const assert = require('node:assert/strict');
const fs = require('node:fs');
const source = fs.readFileSync('gnome-extension/agent-meter@local/extension.js', 'utf8');
const start = source.indexOf('    _refresh() {');
const end = source.indexOf('    _renderState(state) {', start);
const Refresh = eval(`(class {${source.slice(start, end)}})`);
const widget = new Refresh();
let state = {generated_at: '2026-09-12T10:00:00Z', providers: [{id: 'grok', status: 'fresh', windows: [{remaining_percent: 4}]}]};
let renders = 0;
widget._readState = () => structuredClone(state);
widget._renderState = () => { renders++; };
widget._refresh();
for (let i = 0; i < 20; i++) widget._refresh();
assert.equal(renders, 1, 'Unchanged polling must preserve actors');
state.providers[0].windows[0].remaining_percent = 3;
widget._refresh();
assert.equal(renders, 2);
state.generated_at = '2026-09-12T10:05:00Z';
widget._refresh();
assert.equal(renders, 3, 'Update timestamp remains current');
widget._refreshPending = true;
widget._refresh();
widget._refresh();
assert.equal(renders, 4, 'Spinner starts once and is not recreated');
widget._refreshPending = false;
widget._refresh();
assert.equal(renders, 5, 'Spinner clears even when data is unchanged');
widget._desktopVisible = false;
widget._refresh();
assert.equal(renders, 6, 'Menu reflects keyboard visibility changes');
state = null;
widget._dragState = {};
widget._refresh();
assert.equal(renders, 6, 'Drag still defers rendering');
widget._dragState = null;
widget._refresh();
widget._refresh();
assert.equal(renders, 7, 'Missing data renders once');
state = {providers: []};
widget._renderState = () => { throw new Error('render failure'); };
assert.throws(() => widget._refresh());
widget._renderState = () => { renders++; };
widget._refresh();
assert.equal(renders, 8, 'Failed rendering must be retried');
console.log('Change-driven rendering checks passed');
